version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: boltai_api
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: boltai_web
    depends_on:
      - api
    ports:
      - "8080:80"
