services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: boltai_backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: boltai_frontend
    ports:
      - "3000:80"
