name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          cd backend
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: FastAPI smoke
        run: |
          cd backend
          nohup python -m uvicorn backend.main:app --host 127.0.0.1 --port 8000 &
          sleep 5
          curl -s http://127.0.0.1:8000/health || curl -s http://127.0.0.1:8000/api/health || echo "Health check endpoint not found"

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install and build
        run: |
          npm install --legacy-peer-deps
          npm run build
